*: sync with new server/client
hstreamdb/integration-tests pull request #29
Opened 2022-01-28 06:24 UTC by alissa-tung

2022-02-08 05:45 UTC, alissa-tung commented
r+ @s12f @YangKian @Commelina

2022-02-09 03:01 UTC, s12f commented on app/src/test/java/io/hstream/testing/BasicTest.java
> +        hStreamClient.newBufferedProducer().stream(streamName).recordCountLimit(0).build();
recordCountLimit is not allowed to be less than 1, so we should change this test case to assert an expected exception(HStreamDBClientException).

2022-02-09 03:27 UTC, alissa-tung commented on app/src/test/java/io/hstream/testing/BasicTest.java
> +        hStreamClient.newBufferedProducer().stream(streamName).recordCountLimit(0).build();
thx [ad5a784](https://github.com/hstreamdb/integration-tests/pull/29/commits/ad5a784490127844d2699b072ee74a61c08039a3)

2022-02-10 04:43 UTC, YangKian requested changes

2022-02-10 04:43 UTC, YangKian commented on app/src/test/java/io/hstream/testing/TestUtils.java
> +    return Record.newBuilder().rawRecord(randBytes()).build();
return buildRecord(randBytes());

2022-02-10 04:43 UTC, YangKian commented on app/src/test/java/io/hstream/testing/TestUtils.java
> +    if (!input.isEmpty()) {
no need to check here?  call map on an empty list should return an empty list and will be rejected in `isAscending()`  method

2022-02-10 04:43 UTC, YangKian commented on app/src/test/java/io/hstream/testing/BasicTest.java
> +      p.write(Record.newBuilder().rawRecord(rRec).build()).join();
Use the helper function `buildRecord()` in `TestUtil` to avoid writing this directly.

2022-02-10 04:50 UTC, YangKian commented on app/src/test/java/io/hstream/testing/TestUtils.java
> +    if (!input.isEmpty()) {
if you want `assertRecordIdsAscending(emptyList)` success, then modify the implemention of `isAscending()` method.

2022-02-14 07:25 UTC, YangKian approved these changes

2022-02-14 07:26 UTC, merged